---
version: '3.8'

x-defaults:
  # common configurations for the brokers
  broker-environment:
    &broker-environment
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    KAFKA_JMX_PORT: 9101
    KAFKA_JMX_HOSTNAME: localhost
    KAFKA_PROCESS_ROLES: 'broker,controller'
    KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:9093,2@broker-2:9093,3@broker-3:9093'
    KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
    KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    KAFKA_LOG_DIRS: '/data/kafka'
    KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
    CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: 'broker-1:9092,broker-2:9092,broker-3:9092'
    CONFLUENT_METRICS_REPORTER_TOPIC_PARTITIONS: 12
    CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
    CONFLUENT_METRICS_ENABLE: "true"
  broker-configs:
    - &broker-startup ./start-kafka.sh:/tmp/start-kafka.sh
    - &broker-startup-cmd "bash -c 'if [ ! -f /tmp/start-kafka.sh ]; then echo \"ERROR: Did you forget the start-kafka.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/start-kafka.sh && /etc/confluent/docker/run ; fi'"

networks:
  kafka:
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  broker-1:
    image: confluentinc/cp-enterprise-kafka:7.3.1
    hostname: broker-1
    container_name: broker-1
    ports:
      - "9092:9092"
    networks:
      kafka:
        ipv4_address: 172.18.0.11
    environment:
      <<: *broker-environment
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: 'PLAINTEXT://:9192,CONTROLLER://:9093,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:9092,PLAINTEXT_HOST://172.18.0.11:9092'
    env_file:
      - .env
    volumes:
      - *broker-startup
      - ./data/broker-1/:/data/kafka/
    command: *broker-startup-cmd

  broker-2:
    image: confluentinc/cp-enterprise-kafka:7.3.1
    hostname: broker-2
    container_name: broker-2
    ports:
      - "9292:9092"
    networks:
      kafka:
        ipv4_address: 172.18.0.12
    environment:
      <<: *broker-environment
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: 'PLAINTEXT://:9292,CONTROLLER://:9093,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:9092,PLAINTEXT_HOST://172.18.0.12:9092'
    env_file:
      - .env
    volumes:
      - *broker-startup
      - ./data/broker-2/:/data/kafka/
    command: *broker-startup-cmd

  broker-3:
    image: confluentinc/cp-enterprise-kafka:7.3.1
    hostname: broker-3
    container_name: broker-3
    ports:
      - "9392:9092"
    networks:
      kafka:
        ipv4_address: 172.18.0.13
    environment:
      <<: *broker-environment
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: 'PLAINTEXT://:9392,CONTROLLER://:9093,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-3:9092,PLAINTEXT_HOST://172.18.0.13:9092'
    env_file:
      - .env
    volumes:
      - *broker-startup
      - ./data/broker-3/:/data/kafka/
    command: *broker-startup-cmd

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker-1
      - broker-2
      - broker-3
    ports:
      - "8081:8081"
    networks:
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker-1:9092,broker-2:9092,broker-3:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  connect:
    image: cnfldemos/cp-server-connect-datagen:0.6.0-7.3.0
    hostname: connect
    container_name: connect
    depends_on:
      - broker-1
      - broker-2
      - broker-3
      - schema-registry
    ports:
      - "8083:8083"
    networks:
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker-1:9092,broker-2:9092,broker-3:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      # CLASSPATH required due to CC-2422
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.3.1.jar
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker-1
      - broker-2
      - broker-3
      - schema-registry
      - connect
    ports:
      - "9021:9021"
    networks:
      - kafka
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker-1:9092,broker-2:9092,broker-3:9092'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_JMX_OPTS:
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
